### ISSUE TITLE
Please add English comments to codes

### ISSUE THREAD

**Issue by amindadgar** [my000own000files1/Fuzzy#1]
Hi
I've been trying to see how your code works but I wasn't able to understand some of your comments. Please use English comments for codes.

Thanks

**Comment by dvogureckiy99** [comment]
Hi, thanks for watching my code. I am trying to add most of comments in english, but I didn't do it everywhere. Okey, I will see and improve it. But you can say where you didn't understand. The best file with english comments is 'lab3' and branch 'control'.

**Comment by amindadgar** [comment]
Thanks for your time. I tried to read https://github.com/dvogureckiy99/Fuzzy/blob/main/lab2.ipynb but I couldn't figure out what meaning suits the best for each comment.
Please if it is possible translate them into English.

Best regards

**Comment by dvogureckiy99** [comment]
I translated all comments for this file, if you need more, please tell me. I surprised that you figure out this file, because of there is more difficult.
